version: "3"

services:

    software-shinobi-linux:

        container_name: software-shinobi-linux
        
        hostname: software-shinobi

        image: softwareshinobi/software-shinobi-ubuntu-linux:latest

        restart: "always"

        domainname: linux.softwareshinobi.online

        ports:

            - "42022:22"

            - "42080:80"
